services:
  backend:
    context: ./test-fastapi-app/
    dockerfile: Dockerfile
    build: ./test-fastapi-app
    container_name: docker-fastapi
    restart: always

  # frontend:
  #   build: ./test-react-app
  #   # ports:
  #     # - "9000:80"  # Tu PC (9000) -> Contenedor (80)
  #   restart: always

  nginx:
    build: 
      context: ./test-react-app/
      dockerfile: Dockerfile
      # image: docker-compose-for-full-stack-app-farm-frontend:latest
    container_name: nginx_proxy  # Opcional
    ports:
      - "80:80"  # ← ¡ESTE ES EL ÚNICO PUERTO QUE DEBES EXPOSER AHORA!
    # volumes:
    #   - ./test-react-app/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./test-react-app/dist:/usr/share/nginx/html # cuidado con el dockerfile tenga esto y da forbiden
    depends_on:
      - backend
    restart: always